---
name: Build Container on Rust Changes

# Build and push container when Rust files change, using branch name as tag
"on":
  push:
    branches-ignore: []
    paths:
      - 'Cargo.toml'
      - 'Cargo.lock'
      - 'rust-toolchain.toml'
      - 'server/**'
      - 'libs/**'
      - 'proto/**'
      - 'tools/**'
      - 'server/lib-macros/**'
      - 'server/builder.sh'
      - 'server/Dockerfile'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  set_tag_values:
    runs-on: ubuntu-latest
    name: Set image tag values
    steps:
      - id: step1
        run: |
          echo "OWNER_LC=${OWNER,,}" >> "${GITHUB_OUTPUT}"
        env:
          OWNER: '${{ github.repository_owner }}'
      - id: step2
        run: |
          echo "REF_NAME=${REF_NAME,,}" >> "${GITHUB_OUTPUT}"
        env:
          REF_NAME: '${{ github.ref_name }}'
      - id: step3
        run: |
          # Sanitize branch name for use as docker tag (replace / with -)
          echo "TAG_NAME=$(echo ${REF_NAME,,} | sed 's/\//-/g')" >> "${GITHUB_OUTPUT}"
        env:
          REF_NAME: '${{ github.ref_name }}'
    outputs:
      owner_lc: ${{ steps.step1.outputs.OWNER_LC }}
      ref_name: ${{ steps.step2.outputs.REF_NAME }}
      tag_name: ${{ steps.step3.outputs.TAG_NAME }}

  kanidmd_build:
    name: Build kanidmd Docker image
    runs-on: ubuntu-latest
    needs: set_tag_values
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ needs.set_tag_values.outputs.owner_lc }}/kanidmd
          tags: |
            type=ref,event=branch
            type=sha,prefix=
      - name: Build kanidmd
        uses: docker/build-push-action@v6
        with:
          platforms: "linux/amd64"
          tags: ghcr.io/${{ needs.set_tag_values.outputs.owner_lc }}/kanidmd:${{ needs.set_tag_values.outputs.tag_name }}
          build-args: |
            "KANIDM_FEATURES=dev-oauth2-device-flow"
          file: server/Dockerfile
          context: .
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
          # Must use OCI exporter for multi-arch: https://github.com/docker/buildx/pull/1813
          outputs: type=oci,dest=/tmp/kanidmd-docker.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: kanidmd-docker
          path: /tmp/kanidmd-docker.tar

  kanidmd_push:
    name: Push kanidmd Docker image
    runs-on: ubuntu-latest
    needs: [kanidmd_build, set_tag_values]
    permissions:
      packages: write

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v7
        with:
          name: kanidmd-docker
          path: /tmp
      - name: Set up ORAS
        uses: oras-project/setup-oras@v1
      - name: Push image to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | \
            oras login -u "${{ github.actor }}" --password-stdin ghcr.io
          oras copy --from-oci-layout "/tmp/kanidmd-docker.tar:${{ needs.set_tag_values.outputs.tag_name }}" \
            "ghcr.io/${{ needs.set_tag_values.outputs.owner_lc }}/kanidmd:${{ needs.set_tag_values.outputs.tag_name }}"
